//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyCodeMaster
    {
        public int Crncy_ID { get; set; }
        public string Crncy_Code { get; set; }
        public string Crncy_Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Create_On { get; set; }
    }
}
