//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerApproval
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string ApproverRole { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedByDate { get; set; }
    
        public virtual Cust_reg_tbl Cust_reg_tbl { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
