//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTType_Master
    {
        public int GSTyp_ID { get; set; }
        public string GSTType { get; set; }
        public string GSTTypDesc { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
