//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public long id { get; set; }
        public string LogonUser { get; set; }
        public string TempSessionId { get; set; }
        public string IPAddresses { get; set; }
        public Nullable<System.DateTime> Log_on { get; set; }
        public Nullable<System.DateTime> Logout_on { get; set; }
    }
}
