//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lx_AVM
    {
        public int AV_ID { get; set; }
        public string AVM_ID { get; set; }
        public string Vendor_Code { get; set; }
        public string Vendor_Name { get; set; }
        public string Currency_Code { get; set; }
        public string Vendor_Add1 { get; set; }
        public string Vendor_Add2 { get; set; }
        public string Vendor_StateCode { get; set; }
        public string Vendor_Pincode { get; set; }
        public string Vendor_Type { get; set; }
        public string Vendor_ContactName { get; set; }
        public string Vendor_CountryCode { get; set; }
        public string Vendor_PhoneNo { get; set; }
        public string Vendor_EmailAddress { get; set; }
        public string RecDate { get; set; }
    }
}
