//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lx_CustomerMaster
    {
        public int ID { get; set; }
        public string RecID { get; set; }
        public string CustCode { get; set; }
        public string CustName { get; set; }
        public string CustAdd1 { get; set; }
        public string CustAdd2 { get; set; }
        public string CustAdd3 { get; set; }
        public string CustStateCode { get; set; }
        public string CustPincode { get; set; }
        public string CustConuntryCode { get; set; }
        public string CustType { get; set; }
        public string CustPhNo { get; set; }
        public string CustContactName { get; set; }
        public string CurrencyCode { get; set; }
        public string CustEmailAddress { get; set; }
        public string CreatedOnDate { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
    }
}
