//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lx_GSV
    {
        public int GSV_ID { get; set; }
        public string Seg_ID { get; set; }
        public string Dept_Code { get; set; }
        public string Dept_Desc { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
    }
}
