//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orginzation_StatusMaster
    {
        public int OrgZ_ID { get; set; }
        public string Orginzation_Status { get; set; }
        public string OrgCode { get; set; }
        public string OrgCustCode { get; set; }
        public string Orginzation_StsDesc { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
