//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTermsMaster
    {
        public int PTerms_ID { get; set; }
        public string PTerms_Code { get; set; }
        public string PTerms_CodeDesc { get; set; }
        public Nullable<bool> PTerms_Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
