//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Users()
        {
            this.Cust_reg_tbl = new HashSet<Cust_reg_tbl>();
            this.CustomerApprovals = new HashSet<CustomerApproval>();
            this.Vend_reg_tbl = new HashSet<Vend_reg_tbl>();
            this.VendorApprovals = new HashSet<VendorApproval>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int Id { get; set; }
        public string HAID { get; set; }
        public string HAUSER { get; set; }
        public Nullable<int> HACOMP { get; set; }
        public string HANAME { get; set; }
        public string HANEXT { get; set; }
        public string Dept_Code { get; set; }
        public string InitiatorAccess { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string OTP { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cust_reg_tbl> Cust_reg_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerApproval> CustomerApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vend_reg_tbl> Vend_reg_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorApproval> VendorApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
