//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vend_reg_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vend_reg_tbl()
        {
            this.VendorFiles = new HashSet<VendorFile>();
        }
    
        public int ID { get; set; }
        public string Org_Sts { get; set; }
        public string vend_name { get; set; }
        public string CEO_name { get; set; }
        public string Designation { get; set; }
        public string Contact_no { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public Nullable<int> Address1CountryId { get; set; }
        public Nullable<int> Address1StateId { get; set; }
        public Nullable<int> Address1CityId { get; set; }
        public string Address2 { get; set; }
        public Nullable<int> Address2CountryId { get; set; }
        public Nullable<int> Address2StateId { get; set; }
        public Nullable<int> Address2CityId { get; set; }
        public string AC_contact_Desig { get; set; }
        public string AC_contact_name { get; set; }
        public string AC_contact_Phno { get; set; }
        public string AC_contact_Email { get; set; }
        public string Spy_contact_Desig { get; set; }
        public string Spy_contact_name { get; set; }
        public string Spy_contact_Phno { get; set; }
        public string Spy_contact_Email { get; set; }
        public string CIN_No { get; set; }
        public string PAN_No { get; set; }
        public string Type_vend_gst { get; set; }
        public string GST_Reg_no { get; set; }
        public string Item_Desc { get; set; }
        public string HSN_SAC_code { get; set; }
        public string MSME_no { get; set; }
        public Nullable<decimal> Annu_TurnOver { get; set; }
        public string Nature_of_service { get; set; }
        public Nullable<int> FinancialYear1 { get; set; }
        public Nullable<int> FinancialYear2 { get; set; }
        public Nullable<bool> IsITRFiled1 { get; set; }
        public Nullable<bool> IsITRFiled2 { get; set; }
        public string AcknowledgeNo1 { get; set; }
        public string AcknowledgeNo2 { get; set; }
        public string ITR_Field_dtl { get; set; }
        public string Benificiary_name { get; set; }
        public string Bank_name { get; set; }
        public string Branch_name_Add { get; set; }
        public string Account_no { get; set; }
        public Nullable<decimal> MICR_code { get; set; }
        public string IFSC_RTGS_code { get; set; }
        public Nullable<decimal> Date { get; set; }
        public string Type_of_Vend { get; set; }
        public string OTP { get; set; }
        public string NewVendorReason { get; set; }
        public string NewVendorReasonDescription { get; set; }
        public Nullable<bool> Step1 { get; set; }
        public Nullable<bool> Step2 { get; set; }
        public Nullable<bool> Step3 { get; set; }
        public Nullable<bool> Step4 { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual State State { get; set; }
        public virtual State State1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorFile> VendorFiles { get; set; }
    }
}
